language: node_js

node_js:
  - node

branches:
    only:
      - master  # will only build for master branch commits
      - /^greenkeeper/.*$/

before_script:
  - npm install -g --silent firebase-tools # installs firebase to run firebase deploy
  - npm install -g --silent @angular/cli
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

script:
  - ng build --prod

before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile  

install: npm install


after_success:
  # firebase deploy after angular-cli build
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    on_failure: change
    on_success: change